//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_Entity.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONA
    {
        public int IdPersona { get; set; }
        public string Nombres { get; set; }
        public string Telefono { get; set; }
    }
}
